version: '3'
services:
  backend:
    image: node:10.16-alpine
    ports:
      - 3000:3000
    expose:
      - 3000
    user: "1000:1000"
    working_dir: /backend
    volumes:
      - ./src/backend:/backend
    command: sh -c "npm install && DEBUG=backend:* npm start"
    depends_on:
      - database

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
